### PR TITLE
Roles API

### PR DESCRIPTION
**Pull request by Rukomoynikov**

### CODE REVIEW

**Comment by andreibondarev** [comment]
@Rukomoynikov Have you tried running `standardrb --fix`?

**Comment by Rukomoynikov** [comment]
> @Rukomoynikov Have you tried running `standardrb --fix`?

Hi @andreibondarev. Sorry for bothering you. I will fix all the issues and tests. Sorry for the inconveniences.

**Comment by andreibondarev** [comment]
@Rukomoynikov Oh no! Thank you for the great work!

**Comment by Rukomoynikov** [comment]
> @Rukomoynikov Have you tried running `standardrb --fix`?

I should have marked this as draft.

**Comment by andreibondarev** [comment]
@Rukomoynikov Would you please update the README.md as well with examples for the new interfaces?

**Review by andreibondarev — APPROVED** [review]

**Pull request merged**
